/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_0$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_0$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_1$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_1$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_1$schema$value ??= z.string())
let _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_result$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_result$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_result$schema$value ??= z.void())
let _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_0$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_0$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_1$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_1$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_1$schema$value ??= z.string())
let _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_result$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_result$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_getGroup_result$schema$value ??= z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'capsules': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'body': z.string().readonly(),
})).readonly(),
}))
let _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_parameter_0$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_parameter_0$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_result$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_result$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_result$schema$value ??= z.object({
  'groups': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
})).readonly(),
  'adoptedOrphanIds': z.array(z.string()).readonly(),
}))
let _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_0$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_0$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_1$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_1$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_1$schema$value ??= z.array(z.string()))
let _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_result$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_result$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_result$schema$value ??= z.void())
let _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_0$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_0$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_1$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_1$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_1$schema$value ??= z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'capsules': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'body': z.string().readonly(),
})).readonly(),
}))
let _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_result$schema$value
const _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_result$schema = () => (_nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_result$schema$value ??= z.void())

export const TYPERT = {
  package: '@nangeagi/dsh-sop-capsules',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@nangeagi/dsh-sop-capsules#sopCapsules/deleteGroup',
      service: 'sopCapsules',
      namespace: 'sopCapsules',
      method: 'deleteGroup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_0$schema,
          },
        },
        {
          name: 'groupId',
          wire: 'groupId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/deleteGroup:groupId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/deleteGroup:result',
        create: _nangeagi_dsh_sop_capsules_sopCapsules_deleteGroup_result$schema,
      },
      sourceLocation: {"file":"plugins/sop-capsules/src/index.ts","line":81,"column":9},
    },
    {
      id: '@nangeagi/dsh-sop-capsules#sopCapsules/getGroup',
      service: 'sopCapsules',
      namespace: 'sopCapsules',
      method: 'getGroup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_0$schema,
          },
        },
        {
          name: 'groupId',
          wire: 'groupId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/getGroup:groupId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@nangeagi/dsh-sop-capsules/types#SopCapsuleGroup',
        create: _nangeagi_dsh_sop_capsules_sopCapsules_getGroup_result$schema,
      },
      sourceLocation: {"file":"plugins/sop-capsules/src/index.ts","line":55,"column":9},
    },
    {
      id: '@nangeagi/dsh-sop-capsules#sopCapsules/listLibrary',
      service: 'sopCapsules',
      namespace: 'sopCapsules',
      method: 'listLibrary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@nangeagi/dsh-sop-capsules/types#SopLibrarySummary',
        create: _nangeagi_dsh_sop_capsules_sopCapsules_listLibrary_result$schema,
      },
      sourceLocation: {"file":"plugins/sop-capsules/src/index.ts","line":42,"column":9},
    },
    {
      id: '@nangeagi/dsh-sop-capsules#sopCapsules/reorderGroups',
      service: 'sopCapsules',
      namespace: 'sopCapsules',
      method: 'reorderGroups',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_0$schema,
          },
        },
        {
          name: 'groupIds',
          wire: 'groupIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/reorderGroups:groupIds',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/reorderGroups:result',
        create: _nangeagi_dsh_sop_capsules_sopCapsules_reorderGroups_result$schema,
      },
      sourceLocation: {"file":"plugins/sop-capsules/src/index.ts","line":94,"column":9},
    },
    {
      id: '@nangeagi/dsh-sop-capsules#sopCapsules/saveGroup',
      service: 'sopCapsules',
      namespace: 'sopCapsules',
      method: 'saveGroup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_0$schema,
          },
        },
        {
          name: 'group',
          wire: 'group',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@nangeagi/dsh-sop-capsules/types#SopCapsuleGroup',
            create: _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@nangeagi/dsh-sop-capsules#sopCapsules/saveGroup:result',
        create: _nangeagi_dsh_sop_capsules_sopCapsules_saveGroup_result$schema,
      },
      sourceLocation: {"file":"plugins/sop-capsules/src/index.ts","line":68,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote service for workspace SOP capsule library persistence.",
        "summary": "Host Remote service for workspace SOP capsule library persistence.",
        "tags": [],
        "jsDoc": "/** Host Remote service for workspace SOP capsule library persistence. */",
        "key": "sopCapsules",
        "exportName": "SopCapsulesService",
        "members": [
          {
            "kind": "method",
            "name": "listLibrary",
            "signature": "@Remote async listLibrary(sessionId: SessionId, signal: AbortSignal): Promise<SopLibrarySummary>",
            "summary": "List registered groups for the session workspace library.",
            "jsDoc": "/**\n * List registered groups for the session workspace library.\n * @param sessionId - Session whose workspace entity selects the library root.\n * @param signal - caller cancellation.\n */"
          },
          {
            "kind": "method",
            "name": "getGroup",
            "signature": "@Remote async getGroup(sessionId: SessionId, groupId: string, signal: AbortSignal): Promise<SopCapsuleGroup>",
            "summary": "Load one group yaml.",
            "jsDoc": "/**\n * Load one group yaml.\n * @param sessionId - Session whose workspace entity selects the library root.\n * @param groupId - stable group id.\n * @param signal - caller cancellation.\n */"
          },
          {
            "kind": "method",
            "name": "saveGroup",
            "signature": "@Remote async saveGroup(sessionId: SessionId, group: SopCapsuleGroup, signal: AbortSignal): Promise<void>",
            "summary": "Create or replace one group and register new ids on the manifest.",
            "jsDoc": "/**\n * Create or replace one group and register new ids on the manifest.\n * @param sessionId - Session whose workspace entity selects the library root.\n * @param group - full group payload.\n * @param signal - caller cancellation.\n */"
          },
          {
            "kind": "method",
            "name": "deleteGroup",
            "signature": "@Remote async deleteGroup(sessionId: SessionId, groupId: string, signal: AbortSignal): Promise<void>",
            "summary": "Delete one group file and remove it from the manifest.",
            "jsDoc": "/**\n * Delete one group file and remove it from the manifest.\n * @param sessionId - Session whose workspace entity selects the library root.\n * @param groupId - stable group id.\n * @param signal - caller cancellation.\n */"
          },
          {
            "kind": "method",
            "name": "reorderGroups",
            "signature": "@Remote async reorderGroups(sessionId: SessionId, groupIds: readonly string[], signal: AbortSignal): Promise<void>",
            "summary": "Replace manifest group order.",
            "jsDoc": "/**\n * Replace manifest group order.\n * @param sessionId - Session whose workspace entity selects the library root.\n * @param groupIds - ordered ids covering every registered group.\n * @param signal - caller cancellation.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SopCapsule",
            "declaration": "export interface SopCapsule {\n    readonly id: string;\n    readonly title: string;\n    readonly body: string;\n}"
          },
          {
            "name": "SopCapsuleGroup",
            "declaration": "export interface SopCapsuleGroup {\n    readonly id: string;\n    readonly displayName: string;\n    readonly capsules: readonly SopCapsule[];\n}"
          },
          {
            "name": "SopLibraryGroupSummary",
            "declaration": "export interface SopLibraryGroupSummary {\n    readonly id: string;\n    readonly displayName: string;\n}"
          },
          {
            "name": "SopLibrarySummary",
            "declaration": "export interface SopLibrarySummary {\n    readonly groups: readonly SopLibraryGroupSummary[];\n    readonly adoptedOrphanIds: readonly string[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
