/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { SopCapsuleGroup, SopLibrarySummary } from '@nangeagi/dsh-sop-capsules/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736f7043617073756c6573 {
    deleteGroup: (sessionId: SessionId, groupId: string, signal?: AbortSignal) => Promise<RemoteResult<void>>
    getGroup: (sessionId: SessionId, groupId: string, signal?: AbortSignal) => Promise<RemoteResult<SopCapsuleGroup>>
    listLibrary: (sessionId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<SopLibrarySummary>>
    reorderGroups: (sessionId: SessionId, groupIds: readonly string[], signal?: AbortSignal) => Promise<RemoteResult<void>>
    saveGroup: (sessionId: SessionId, group: SopCapsuleGroup, signal?: AbortSignal) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'sopCapsules/deleteGroup': (sessionId: SessionId, groupId: string, signal?: AbortSignal) => Promise<RemoteResult<void>>
    'sopCapsules/getGroup': (sessionId: SessionId, groupId: string, signal?: AbortSignal) => Promise<RemoteResult<SopCapsuleGroup>>
    'sopCapsules/listLibrary': (sessionId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<SopLibrarySummary>>
    'sopCapsules/reorderGroups': (sessionId: SessionId, groupIds: readonly string[], signal?: AbortSignal) => Promise<RemoteResult<void>>
    'sopCapsules/saveGroup': (sessionId: SessionId, group: SopCapsuleGroup, signal?: AbortSignal) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'sopCapsules': TypertRemoteNamespace$736f7043617073756c6573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
